# Generated by Django 4.0.3 on 2022-04-03 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('username', models.CharField(max_length=64)),
                ('phash', models.CharField(max_length=64)),
                ('fname', models.CharField(max_length=64)),
                ('lname', models.CharField(max_length=64)),
            ],
        ),
    ]
